---
- name: Setting all
  hosts: test_hosts
  become: yes

  tasks:
    - name: Clone git repository
      git:
        repo: https://github.com/RaZZario/netdata.git
        dest: /home/netdata/git
        version: master
      become: yes
      become_user: netdata
    
    - name: Change directory to repo
      ansible.builtin.command: cd /home/netdata/git
      become: yes

    - name: Build Docker image
      ansible.builtin.command: >-
        docker run -d --name=netdata \
          -p 19999:19999 \
          -v netdataconfig:/etc/netdata \
          -v netdatalib:/var/lib/netdata \
          -v netdatacache:/var/cache/netdata \
          -v /etc/passwd:/host/etc/passwd:ro \
          -v /etc/group:/host/etc/group:ro \
          -v /proc:/host/proc:ro \
          -v /sys:/host/sys:ro \
          -v /etc/os-release:/host/etc/os-release:ro \
          --restart unless-stopped \
          --cap-add SYS_PTRACE \
          --security-opt apparmor=unconfined \
          netdata/netdata